# Generated by Django 5.2.4 on 2025-07-12 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('toplam_fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('odendi', 'Ödendi'), ('gonderildi', 'Gönderildi')], default='bekliyor', max_length=20)),
                ('adres', models.TextField()),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('aciklama', models.TextField()),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok', models.IntegerField(default=0)),
                ('tavsiye_edilen_tur', models.CharField(blank=True, choices=[('kopek', 'Köpek'), ('kedi', 'Kedi'), ('diger', 'Diğer')], max_length=20)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.kategori')),
            ],
        ),
        migrations.CreateModel(
            name='SiparisKalemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.IntegerField(default=1)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='shop.siparis')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.urun')),
            ],
        ),
        migrations.CreateModel(
            name='UrunResim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='urunler/')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resimler', to='shop.urun')),
            ],
        ),
    ]
