# Generated by Django 5.2.4 on 2025-07-13 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_urun_indirimli_fiyat_urun_kisa_aciklama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urun',
            name='indirimli_fiyat',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='kisa_aciklama',
        ),
    ]
