# Generated by Django 5.2.4 on 2025-07-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_urun_indirimli_fiyat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='indirimli_fiyat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='urun',
            name='kisa_aciklama',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
