# Generated by Django 5.2.4 on 2025-09-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineSatis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satis_sayisi', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Online Satış Sayacı',
                'verbose_name_plural': 'Online Satış Sayaçları',
            },
        ),
    ]
