"""
Django settings for courseapp project.
Generated by 'django-admin startproject' using Django 4.2.
"""

import os
from pathlib import Path

# Baz dizin
BASE_DIR = Path(__file__).resolve().parent.parent

# Geliştirme ayarları
SECRET_KEY = 'django-insecure-$1!qju8gp_pq9!64se@y!n-h!=@f3%xgf(sx9*o43i$696k(4t'
DEBUG = True
ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

# Site URL (QR linkleri vb. için kullanılıyor)
SITE_URL = 'http://127.0.0.1:8000'

# Uygulamalar
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Proje uygulamaları
    'anahtarlik',
    'accaunt',
    'shop',
    'widget_tweaks',
    'petpanel',
    'etiket',
    'veteriner',
    'petshop',
]

LOGIN_URL = '/accaunt/login/'

# Orta katmanlar
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Profil tamamlama yönlendirmesi (TEK KEZ!)
    'courseapp.middleware.ProfileCompletionMiddleware',
]

# URL ve WSGI
ROOT_URLCONF = 'courseapp.urls'
WSGI_APPLICATION = 'courseapp.wsgi.application'

# Şablonlar
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Proje kökündeki templates klasörü
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # Sepet özeti (shop ile entegre)
                'courseapp.context_processors.sepet_ozeti',
            ],
        },
    },
]

# Veritabanı (SQLite - geliştirici ortamı)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME'  : BASE_DIR / 'db.sqlite3',
    }
}

# Şifre doğrulama
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Uluslararasılaştırma
LANGUAGE_CODE = 'tr'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Statik ve medya dosyaları
STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_URL = '/static/'  # tavsiye edilen kullanım
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Varsayılan PK tipi
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# E-posta (Gmail SMTP)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "sercan.20030@gmail.com"          # geliştirme amaçlı
EMAIL_HOST_PASSWORD = "rsef uohy ijtj kpsp"         # geliştirme amaçlı
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Loglama
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {'console': {'class': 'logging.StreamHandler'}},
    'root': {'handlers': ['console'], 'level': 'INFO'},
}
