# Generated by Django 5.2.4 on 2025-07-10 21:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvcilHayvan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('tur', models.CharField(choices=[('kopek', 'Köpek'), ('kedi', 'Kedi'), ('diger', 'Diğer')], max_length=20)),
                ('cins', models.CharField(max_length=100)),
                ('saglik_bilgisi', models.TextField(blank=True)),
                ('beslenme_bilgisi', models.TextField(blank=True)),
                ('davranis_notlari', models.TextField(blank=True)),
                ('kayip_durumu', models.BooleanField(default=False)),
                ('kayip_bildirim_tarihi', models.DateTimeField(blank=True, null=True)),
                ('odul_miktari', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etiket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiket_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('seri_numarasi', models.CharField(max_length=50, unique=True)),
                ('qr_kod_url', models.URLField(blank=True)),
                ('aktif', models.BooleanField(default=False)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('evcil_hayvan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anahtarlik.evcilhayvan')),
            ],
        ),
        migrations.CreateModel(
            name='BeslenmeKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('besin_turu', models.CharField(max_length=100)),
                ('tarih', models.DateField()),
                ('miktar', models.CharField(max_length=50)),
                ('notlar', models.TextField(blank=True)),
                ('evcil_hayvan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beslenme_kayitlari', to='anahtarlik.evcilhayvan')),
            ],
        ),
        migrations.CreateModel(
            name='SaglikKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asi_turu', models.CharField(max_length=100)),
                ('asi_tarihi', models.DateField()),
                ('notlar', models.TextField(blank=True)),
                ('evcil_hayvan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saglik_kayitlari', to='anahtarlik.evcilhayvan')),
            ],
        ),
        migrations.CreateModel(
            name='Sahip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(blank=True, max_length=15)),
                ('adres', models.TextField(blank=True)),
                ('acil_durum_kontagi', models.CharField(blank=True, max_length=15)),
                ('kullanici', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='evcilhayvan',
            name='sahip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evcil_hayvanlar', to='anahtarlik.sahip'),
        ),
    ]
