# Generated by Django 5.2.4 on 2025-07-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiket',
            name='kilitli',
            field=models.BooleanField(default=False),
        ),
    ]
