# Generated by Django 5.2.4 on 2025-07-11 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0002_etiket_kilitli'),
    ]

    operations = [
        migrations.AddField(
            model_name='evcilhayvan',
            name='cinsiyet',
            field=models.CharField(choices=[('erkek', 'Erkek'), ('disi', 'Dişi'), ('bilinmiyor', 'Bilinmiyor')], default='bilinmiyor', max_length=20),
        ),
        migrations.AddField(
            model_name='evcilhayvan',
            name='dogum_tarihi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evcilhayvan',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='evcil_hayvanlar/'),
        ),
        migrations.AddField(
            model_name='sahip',
            name='ad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sahip',
            name='soyad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sahip',
            name='yedek_telefon',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.CreateModel(
            name='Alerji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alerji_turu', models.CharField(max_length=100)),
                ('aciklama', models.TextField(blank=True)),
                ('kaydedilme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('evcil_hayvan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerjiler', to='anahtarlik.evcilhayvan')),
            ],
        ),
        migrations.CreateModel(
            name='AmeliyatKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ameliyat_turu', models.CharField(max_length=100)),
                ('tarih', models.DateField()),
                ('veteriner', models.CharField(blank=True, max_length=100)),
                ('notlar', models.TextField(blank=True)),
                ('evcil_hayvan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ameliyat_kayitlari', to='anahtarlik.evcilhayvan')),
            ],
        ),
        migrations.CreateModel(
            name='AsiTakvimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asi_turu', models.CharField(max_length=100)),
                ('planlanan_tarih', models.DateField()),
                ('tamamlandi', models.BooleanField(default=False)),
                ('tamamlanma_tarihi', models.DateField(blank=True, null=True)),
                ('notlar', models.TextField(blank=True)),
                ('evcil_hayvan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asi_takvimi', to='anahtarlik.evcilhayvan')),
            ],
        ),
        migrations.CreateModel(
            name='IlacKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilac_adi', models.CharField(max_length=100)),
                ('baslangic_tarihi', models.DateField()),
                ('bitis_tarihi', models.DateField(blank=True, null=True)),
                ('dozaj', models.CharField(blank=True, max_length=50)),
                ('notlar', models.TextField(blank=True)),
                ('evcil_hayvan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilac_kayitlari', to='anahtarlik.evcilhayvan')),
            ],
        ),
        migrations.CreateModel(
            name='KiloKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tarih', models.DateField()),
                ('notlar', models.TextField(blank=True)),
                ('evcil_hayvan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kilo_kayitlari', to='anahtarlik.evcilhayvan')),
            ],
        ),
    ]
