# Generated by Django 5.2.4 on 2025-07-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0003_evcilhayvan_cinsiyet_evcilhayvan_dogum_tarihi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evcilhayvan',
            name='genel_notlar',
            field=models.TextField(blank=True),
        ),
    ]
