# Generated by Django 5.2.4 on 2025-07-22 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0004_evcilhayvan_genel_notlar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evcilhayvan',
            old_name='beslenme_bilgisi',
            new_name='beslenme_notu',
        ),
        migrations.RenameField(
            model_name='evcilhayvan',
            old_name='davranis_notlari',
            new_name='davranis_notu',
        ),
        migrations.RenameField(
            model_name='evcilhayvan',
            old_name='genel_notlar',
            new_name='genel_not',
        ),
        migrations.RenameField(
            model_name='evcilhayvan',
            old_name='saglik_bilgisi',
            new_name='saglik_notu',
        ),
    ]
