# Generated by Django 5.2.4 on 2025-08-03 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0005_rename_beslenme_bilgisi_evcilhayvan_beslenme_notu_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kilokaydi',
            options={'verbose_name': 'Kilo Kaydı', 'verbose_name_plural': 'Kilo Kayıtları'},
        ),
        migrations.AlterField(
            model_name='kilokaydi',
            name='kilo',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
