# Generated by Django 5.2.4 on 2025-09-04 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0006_alter_kilokaydi_options_alter_kilokaydi_kilo'),
        ('petshop', '0001_initial'),
        ('veteriner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='etiket',
            name='aktiflestiren',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aktiflestirdigi_etiketler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='etiket',
            name='aktiflestirme_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etiket',
            name='first_activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etiket',
            name='kanal',
            field=models.CharField(blank=True, choices=[('ONLINE', 'Online'), ('VET', 'Veteriner'), ('SHOP', 'Petshop')], max_length=10),
        ),
        migrations.AddField(
            model_name='etiket',
            name='satici_petshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sattigi_etiketler', to='petshop.petshop'),
        ),
        migrations.AddField(
            model_name='etiket',
            name='satici_veteriner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sattigi_etiketler', to='veteriner.veteriner'),
        ),
        migrations.AddField(
            model_name='etiket',
            name='tahsis_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='etiket',
            constraint=models.CheckConstraint(condition=models.Q(('kanal__isnull', True), models.Q(('kanal', 'VET'), _negated=True), ('satici_veteriner__isnull', False), _connector='OR'), name='etiket_vet_icin_veteriner_zorunlu'),
        ),
        migrations.AddConstraint(
            model_name='etiket',
            constraint=models.CheckConstraint(condition=models.Q(('kanal__isnull', True), models.Q(('kanal', 'SHOP'), _negated=True), ('satici_petshop__isnull', False), _connector='OR'), name='etiket_shop_icin_petshop_zorunlu'),
        ),
        migrations.AddConstraint(
            model_name='etiket',
            constraint=models.CheckConstraint(condition=models.Q(('kanal__isnull', True), models.Q(('kanal', 'ONLINE'), _negated=True), models.Q(('satici_veteriner__isnull', True), ('satici_petshop__isnull', True)), _connector='OR'), name='etiket_online_icin_partner_bos'),
        ),
    ]
