# Generated by Django 5.2.4 on 2025-09-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0007_etiket_aktiflestiren_etiket_aktiflestirme_tarihi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiket',
            name='aktivasyon_sayisi',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
