# Generated by Django 5.2.4 on 2025-09-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0008_etiket_aktivasyon_sayisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiket',
            name='kanal',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('VET', 'Veteriner'), ('SHOP', 'Petshop')], max_length=10),
        ),
    ]
