# Generated by Django 5.2.4 on 2025-09-07 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0009_alter_etiket_kanal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktif', models.BooleanField(default=True)),
                ('il', models.CharField(blank=True, max_length=50)),
                ('ilce', models.CharField(blank=True, max_length=50)),
                ('ebat', models.CharField(choices=[('kucuk', 'Küçük'), ('orta', 'Orta'), ('buyuk', 'Büyük')], max_length=10)),
                ('tercih_edilen_ebat', models.CharField(blank=True, choices=[('kucuk', 'Küçük'), ('orta', 'Orta'), ('buyuk', 'Büyük')], max_length=10)),
                ('tercih_edilen_irk', models.CharField(blank=True, max_length=100)),
                ('tercih_min_yas_ay', models.PositiveIntegerField(blank=True, null=True)),
                ('tercih_max_yas_ay', models.PositiveIntegerField(blank=True, null=True)),
                ('kisir', models.BooleanField(default=False)),
                ('disi_kizginlik_durumu', models.CharField(choices=[('bilinmiyor', 'Bilinmiyor'), ('aktif', 'Aktif/Kızgınlıkta'), ('degil', 'Kızgınlıkta değil')], default='bilinmiyor', max_length=20)),
                ('asi_tam', models.BooleanField(default=False)),
                ('saglik_notu', models.TextField(blank=True)),
                ('mizac', models.CharField(choices=[('sakin', 'Sakin'), ('enerjik', 'Enerjik'), ('dengeli', 'Dengeli')], default='dengeli', max_length=10)),
                ('notlar', models.TextField(blank=True)),
                ('stud_var', models.BooleanField(default=False)),
                ('stud_ucret', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='ciftlesme/')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='ciftlesme/')),
                ('foto3', models.ImageField(blank=True, null=True, upload_to='ciftlesme/')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncelleme', models.DateTimeField(auto_now=True)),
                ('evcil_hayvan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ciftlesme_profili', to='anahtarlik.evcilhayvan')),
            ],
        ),
        migrations.CreateModel(
            name='MatingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(choices=[('beklemede', 'Beklemede'), ('kabul', 'Kabul'), ('red', 'Red')], default='beklemede', max_length=10)),
                ('mesaj', models.TextField(blank=True)),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncelleme', models.DateTimeField(auto_now=True)),
                ('gonderen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gonderilen_ciftlesme_istekleri', to='anahtarlik.evcilhayvan')),
                ('hedef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alinan_ciftlesme_istekleri', to='anahtarlik.evcilhayvan')),
            ],
            options={
                'ordering': ['-olusturulma'],
                'constraints': [models.CheckConstraint(condition=models.Q(('gonderen', models.F('hedef')), _negated=True), name='matingrequest_gonderen_hedef_farkli')],
            },
        ),
    ]
