# Generated by Django 5.2.4 on 2025-09-07 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0010_matingprofile_matingrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField()),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('gonderen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('istek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesajlar', to='anahtarlik.matingrequest')),
            ],
            options={
                'ordering': ['olusturulma'],
            },
        ),
    ]
