# Generated by Django 5.2.6 on 2025-09-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0020_sahip_location_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sahip',
            name='profil_fotografi',
            field=models.ImageField(blank=True, null=True, upload_to='profil/'),
        ),
    ]
