# Generated by Django 5.2.6 on 2025-09-14 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0021_sahip_profil_fotografi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Il',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Tur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['ad'],
            },
        ),
        # Eski Mating* yapısına müdahale ETME: DB'de mevcut durum farklı olabilir.
        migrations.CreateModel(
            name='Ilce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=120)),
                ('il', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilceler', to='anahtarlik.il')),
            ],
            options={
                'ordering': ['il__ad', 'ad'],
                'unique_together': {('il', 'ad')},
            },
        ),
        migrations.CreateModel(
            name='Cins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=120)),
                ('tur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinsler', to='anahtarlik.tur')),
            ],
            options={
                'ordering': ['tur__ad', 'ad'],
                'unique_together': {('tur', 'ad')},
            },
        ),
        # Eski Mating* modellerini silmiyoruz; ayrı temizlikte ele alınacak.
    ]
