# Generated by Django 5.2.6 on 2025-09-14 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0022_il_tur_remove_matingprofile_evcil_hayvan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evcilhayvan',
            name='cins_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hayvanlar', to='anahtarlik.cins'),
        ),
        migrations.AddField(
            model_name='evcilhayvan',
            name='tur_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hayvanlar', to='anahtarlik.tur'),
        ),
        migrations.AddField(
            model_name='sahip',
            name='il_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sahipleri', to='anahtarlik.il'),
        ),
        migrations.AddField(
            model_name='sahip',
            name='ilce_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sahipleri', to='anahtarlik.ilce'),
        ),
    ]
