# Generated by Django 5.2.4 on 2025-09-04 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Veteriner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=150)),
                ('telefon', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('il', models.CharField(blank=True, max_length=50)),
                ('ilce', models.CharField(blank=True, max_length=50)),
                ('adres_detay', models.TextField(blank=True)),
                ('aktif', models.BooleanField(default=True)),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('tahsis_sayisi', models.PositiveIntegerField(default=0)),
                ('satis_sayisi', models.PositiveIntegerField(default=0)),
                ('kullanici', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veteriner_profili', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Veteriner',
                'verbose_name_plural': 'Veterinerler',
                'ordering': ['ad'],
            },
        ),
    ]
