# Generated by Django 5.2.4 on 2025-09-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veteriner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veteriner',
            name='odeme_modeli',
            field=models.CharField(choices=[('PESIN', 'Peşin Ödeme'), ('KONSINYE', 'Konsinye (Numune) Ödeme')], default='PESIN', max_length=10),
        ),
    ]
