# Generated by Django 5.2.4 on 2025-09-06 12:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veteriner', '0002_veteriner_odeme_modeli'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veteriner',
            options={},
        ),
        migrations.CreateModel(
            name='SiparisIstemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talep_edilen_adet', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('talep_tarihi', models.DateTimeField(auto_now_add=True)),
                ('onaylandi', models.BooleanField(default=False)),
                ('onay_tarihi', models.DateTimeField(blank=True, null=True)),
                ('veteriner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siparis_istekleri', to='veteriner.veteriner')),
            ],
        ),
    ]
