# Generated by Django 5.2.4 on 2025-09-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veteriner', '0003_alter_veteriner_options_siparisistemi'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparisistemi',
            name='adres_detay',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siparisistemi',
            name='farkli_adres_kullan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siparisistemi',
            name='il',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='siparisistemi',
            name='ilce',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
