# Generated by Django 5.2.4 on 2025-09-06 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veteriner', '0004_siparisistemi_adres_detay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparisistemi',
            name='talep_edilen_adet',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(5)]),
        ),
    ]
