# Generated by Django 5.2.4 on 2025-09-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veteriner', '0005_alter_siparisistemi_talep_edilen_adet'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparisistemi',
            name='kargo_sirketi',
            field=models.CharField(blank=True, choices=[('ARAS', 'Aras Kargo'), ('YURTICI', 'Yurtiçi Kargo'), ('MNG', 'MNG Kargo'), ('DHL', 'DHL')], max_length=20),
        ),
        migrations.AddField(
            model_name='siparisistemi',
            name='kargo_takip_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='siparisistemi',
            name='kargo_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siparisistemi',
            name='kargolandimi',
            field=models.BooleanField(default=False),
        ),
    ]
