# Generated by Django 5.2.4 on 2025-09-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veteriner', '0006_siparisistemi_kargo_sirketi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparisistemi',
            name='numune_mi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siparisistemi',
            name='odeme_alinma_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siparisistemi',
            name='odeme_durumu',
            field=models.CharField(choices=[('BEKLEMEDE', 'Beklemede'), ('ALINDI', 'Alındı'), ('IADE', 'İade Edildi'), ('MUAF', 'Muaf (Numune)')], default='BEKLEMEDE', max_length=12),
        ),
        migrations.AddField(
            model_name='siparisistemi',
            name='odeme_para_birimi',
            field=models.CharField(default='TRY', max_length=6),
        ),
        migrations.AddField(
            model_name='siparisistemi',
            name='odeme_tutari',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='siparisistemi',
            name='odeme_yontemi',
            field=models.CharField(blank=True, choices=[('NAKIT', 'Nakit'), ('EFT', 'EFT/Havale'), ('KREDI', 'Kredi Kartı'), ('POS', 'Pos/Link'), ('DIGER', 'Diğer')], max_length=10),
        ),
    ]
